### ISSUE TITLE
make the translucent background darker?

### ISSUE THREAD

**Issue by damienkeating** [owlstanding-labs/weekly-exhibition#15]
30% darker shall be OK

**Comment by damienkeating** [comment]
![img_0075](https://cloud.githubusercontent.com/assets/3681983/12331486/a7a41534-bae1-11e5-9308-a6f5c8320366.PNG)

**Comment by speed-of-light** [comment]
is this ok?
![image](https://cloud.githubusercontent.com/assets/2149541/12333224/eb891a82-bb2d-11e5-9016-d7d9e2948127.png)

**Comment by damienkeating** [comment]
ok
