### ISSUE TITLE
Provide ionic icon for ios app

### ISSUE THREAD

**Issue by speed-of-light** [owlstanding-labs/weekly-exhibition#2]
@damienkeating

**Comment by damienkeating** [comment]
![image](https://cloud.githubusercontent.com/assets/3681983/12121305/80805b14-b3cc-11e5-93b3-fef3ee2abd65.png)

The icon names can be found on: https://creator.ionic.io/app/dashboard/projects

Seems now we have 3 icons:
ion-android-arrow-forward
ion-android-arrow-back
ion-ios-information

**Comment by speed-of-light** [comment]
sorry I mean the `logo` like this:
![image](https://cloud.githubusercontent.com/assets/2149541/12121391/f8fb9306-b3cc-11e5-9dd8-96c7d4931673.png)

in case you don't want to use it.

**Comment by speed-of-light** [comment]
it will appear somewhere like:
![image](https://cloud.githubusercontent.com/assets/2149541/12121415/1cf25c9a-b3cd-11e5-82c0-d9c4a3603397.png)

**Comment by damienkeating** [comment]
https://drive.google.com/open?id=0ByrYZZ-TPMssOG1FWmdCTWUyV1E

**Comment by speed-of-light** [comment]
:+1:
