### ISSUE TITLE
ipad mockup

### ISSUE THREAD

**Issue by damienkeating** [owlstanding-labs/weekly-exhibition#5]
![ipad-mockup](https://cloud.githubusercontent.com/assets/3681983/12223495/13524c10-b7d1-11e5-8450-ebea1883d96d.jpg)

when information page is tapped:
![ipad-mockup3](https://cloud.githubusercontent.com/assets/3681983/12224223/fef8bb34-b7e2-11e5-94f1-6b5db2d0f801.jpg)

To deliver this mockup, these tasks need to be done:
- [x] make the taps black
- [x] load Exhibition name & artist name
- [ ] remove the zoom in, zoom out, reset buttons (not priority, can skip it not and put it to the 1.1.0)
- [x] add information text - just plain text is fine, and translucent background

**Comment by damienkeating** [comment]
seems we can pull translucent element to display our information texts?
![image](https://cloud.githubusercontent.com/assets/3681983/12224216/c57d9f00-b7e2-11e5-851a-9f6fc05b95d9.png)
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/index.html#//apple_ref/doc/uid/TP40006556-CH66-SW1

**Comment by damienkeating** [comment]
This link might be relevant to the translucent screen: http://www.gitshah.com/2014/11/how-to-show-realtime-translucent.html

**Comment by speed-of-light** [comment]
The 3rd task should be done in [website] or build in later version.
