### ISSUE TITLE
Detect WiFi connection

### ISSUE THREAD

**Issue by damienkeating** [owlstanding-labs/weekly-exhibition#9]
Detect WiFi connection, if there is no WiFi connection, display an image like this:
![notification](https://cloud.githubusercontent.com/assets/3681983/12240955/2afcfa1a-b888-11e5-8828-b97b8191325a.jpg)

This is the raw image, in case we need Apple to translate this sentence:
WiFi is not connected.
To load our exhibitions, please connect to your WiFi.
![notification_raw](https://cloud.githubusercontent.com/assets/3681983/12240989/62eb334c-b888-11e5-8ffc-507203acc660.jpg)

**Comment by damienkeating** [comment]
maybe relevant: http://ngcordova.com/docs/plugins/network/

**Comment by damienkeating** [comment]
Please change the wording here:

_You appear to be offline.
To load our exhibitions, please connect to the internet._

![notification](https://cloud.githubusercontent.com/assets/3681983/12241579/ee168a36-b88b-11e5-8578-ef87b4cfa620.jpg)

**Comment by speed-of-light** [comment]
we'll need to check whether the owlstand.com is reachable as well.
